"""add last_pinged_at column in monitors table

Revision ID: 7dde3305efc5
Revises: cdd49d05f376
Create Date: 2026-08-05 18:41:14.421869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dde3305efc5'
down_revision: Union[str, Sequence[str], None] = 'cdd49d05f376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitors', sa.Column('last_pinged_at', postgresql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitors', 'last_pinged_at')
    # ### end Alembic commands ###
