"""add tables apis, urls, monitors, pings

Revision ID: cdd49d05f376
Revises: 
Create Date: 2026-08-03 13:29:14.147188

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdd49d05f376'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apis',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('urls',
                    sa.Column(
                        'url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('api_id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              nullable=True),
                    sa.ForeignKeyConstraint(['api_id'], ['apis.id'], ),
                    sa.PrimaryKeyConstraint('url')
                    )
    op.create_table('monitors',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column(
                        'url_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('interval', sa.Float(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              nullable=True),
                    sa.ForeignKeyConstraint(['url_id'], ['urls.url'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('pings',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('monitor_id', sa.Uuid(), nullable=False),
                    sa.Column('status_code', sa.Integer(), nullable=False),
                    sa.Column('response_time', sa.Float(), nullable=False),
                    sa.Column('is_up', sa.Boolean(), nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              nullable=True),
                    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pings')
    op.drop_table('monitors')
    op.drop_table('urls')
    op.drop_table('apis')
    # ### end Alembic commands ###
